- name: Configuring hostname
  ansible.builtin.shell: set-hostname vault

- name: Installing yum utils
  ansible.builtin.shell: yum install -y yum-utils

- name: Configuring hashicorp repos
  ansible.builtin.shell: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

- name: Installing Vault
  ansible.builtin.dnf:
    name: vault 
    state: installed

- name: Starting vault service
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true

